### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by Sh1d0w** [nodegui/react-nodegui#1]
Running `npm install` yields the following error:

error Couldn't find package "@nodegui/qode@^1.0.0" required by "@nodegui/nodegui@^0.1.1" on the "npm" registry.

**Comment by master-atul** [comment]
That is strange. Is this happening with the react-nodegui-starter repo ? @Sh1d0w

**Comment by Sh1d0w** [comment]
Hey, yes I wanted to try the react repo. If I search for such package in the npmjs website there is also no match. Are you sure the package is publicly accessible?

**Comment by master-atul** [comment]
Wow that was the most embarrasing mistake I did. Thanks for pointing out! I have made everything public now. Cheers

**Comment by master-atul** [comment]
I hope it works now 😄  . I am going to close this issue
