### ISSUE TITLE
Nested window support (Modals or Dialogs)

### ISSUE THREAD

**Issue by mrxdst** [nodegui/react-nodegui#108]
**Describe the bug**
Opening and closing new windows doesn't work properly when nested inside another window

**To Reproduce**
Run the following example code
````tsx
import React, { useState } from "react";
import { Renderer, Window, View, Button, Text } from "@nodegui/react-nodegui";

function MainWindow() {
  const [open1, setOpen1] = useState(false);
  const [open2, setOpen2] = useState(false);
  const [open3, setOpen3] = useState(false);

  return (
    <>
      <Window windowTitle="Main window">
        <View>
          <Button text="Nested in view"   on={{clicked: () => setOpen1(!open1)}}/>
          <Button text="Nested in window" on={{clicked: () => setOpen2(!open2)}}/>
          <Button text="Not nested"       on={{clicked: () => setOpen3(!open3)}}/>
          {open1 && <Dialog text="Nested in view"/>}{/* Does not work */}
        </View>
        {open2 && <Dialog text="Nested in window"/>}{/* Partialy working */}
      </Window>
      {open3 && <Dialog text="Not nested"/>}{/* This works */}
    </>
  );
}

function Dialog({text}: {text: string}) {
  return (
    <Window windowTitle={text}>
      <View>
        <Text>{text}</Text>
      </View>
    </Window>
  )
}

Renderer.render(<MainWindow />);
````

**Expected behavior**
That windows can be open and closed no matter where they are placed in the react tree.

**Desktop (please complete the following information):**
 - OS: Linux
 - NodeGUI version: 0.12.1
 - React NodeGUI version: 0.4.0 
 - OS Version: Arch Linux

**Comment by master-atul** [comment]
Hi @mrxdst 

A QMainWindow (Window) cannot be a child of another QMainWindow
Thats why you can only have multiple top level windows and not nested windows.

What you are looking for is support for QDialog or modals. That has not yet been exported from NodeGui to React NodeGui. 

If you want the QDialog behaviour immediately, maybe you can help export it out in React NodeGui ?

Otherwise I can do it when time permits.

**Comment by mrxdst** [comment]
@master-atul 

Ok, I understand. I do not need this immediately.

**Comment by mako87** [comment]
+1
