### ISSUE TITLE
How to get value from ComboBox

### ISSUE THREAD

**Issue by manashathparia** [nodegui/react-nodegui#109]
how to get the selected value from ComboBox? also, is there any event listeners for change?

**Comment by master-atul** [comment]
https://docs.nodegui.org/docs/api/generated/interfaces/qcomboboxsignals

Can you see if one of these signals would work for you?

**Comment by hrishikesh235** [comment]
Already got it thanks :).

**Comment by manashathparia** [comment]
Already got it thanks :)
