### ISSUE TITLE
setProperties on componenets

### ISSUE THREAD

**Issue by gluaxspeed** [nodegui/react-nodegui#112]
When creating a component it would be a nice feature to be able to set any other properties that we might want. 
For example,
```javascript
const windowProps = {WA_TranslucentBackground: true};
<Window setProperties={windowProps}>
...
</Window>
```
or any of the other widgetAttributes. 

That way we can always pass all the attributes we want to set at once, and you don't have to make a property on the component for every possible attribute.

Edit: Might actually be better to name it setAttributes.

**Comment by master-atul** [comment]
Hi @gluaxspeed 
This functionality already exists.

Example code: 
```
      <Window
        attributes={{ [WidgetAttribute.WA_TranslucentBackground]: true }}
        windowFlags={{ [WindowType.Dialog]: true }}
        windowIcon={winIcon}
        windowTitle="Hello 👋🏽"
      > </Window>
```

**Comment by master-atul** [comment]
I have updated the docs to reflect this. Functionality exists already.

**Comment by gluaxspeed** [comment]
Oh great! Sorry I didn't see that functionality by looking at the source. I must have overlooked it. Cheers for the docs updates though thanks!
