### ISSUE TITLE
Example calculator not work

### ISSUE THREAD

**Issue by quaj** [nodegui/react-nodegui#13]
I'm testing calculator but it throw a error typing 😭

![image](https://user-images.githubusercontent.com/16853175/63259244-0ffc5480-c2a8-11e9-8289-f7b6b5a679ad.png)

**Comment by raajnadar** [comment]
Try `npm run start` maybe this will work

**Comment by quaj** [comment]
> Try `npm run start` maybe this will work

still throw error, i tried remove and install again `@types/react` but seems not work

![image](https://user-images.githubusercontent.com/16853175/63261585-0d046280-c2ae-11e9-9afd-8a14d3ed361a.png)

**Comment by mikaello** [comment]
This example you are trying to run, https://github.com/nodegui/examples/tree/master/react-nodegui/calculator ? It works here with `yarn` on OSX Mojave:
<img width="612" alt="Skjermbilde 2019-08-19 kl  13 37 14" src="https://user-images.githubusercontent.com/2505178/63262589-a6b81980-c286-11e9-8fed-0e30798cec58.png">

**Comment by quaj** [comment]
@mikaello yes i use this example

**Comment by idoo** [comment]
try to run `yarn --no-lockfile`
works for me as well

**Comment by quaj** [comment]
> try to run `yarn --no-lockfile`
> works for me as well

![image](https://user-images.githubusercontent.com/16853175/63273798-d25bf380-c2c8-11e9-995b-aa46c674d956.png)

still not works 🤧

**Comment by master-atul** [comment]
Hi the errors mentiones that you have duplicate versions of `@types/react`

Are you running this via the new repo: https://github.com/nodegui/examples

I had moved the examples there to avoid problems like these. 

If you take a pull of the react nodegui repo. You will not find examples there.

**Comment by master-atul** [comment]
You could try the example from https://github.com/nodegui/examples and report back if you face same issue. @quaj

**Comment by quaj** [comment]
> You could try the example from [nodegui/examples](https://github.com/nodegui/examples) and report back if you face same issue. @quaj

I'm testing in a clone from [nodegui/examples](https://github.com/nodegui/examples) nah

![image](https://user-images.githubusercontent.com/16853175/63274615-4cd94300-c2ca-11e9-88ab-4c881246988a.png)

**Comment by master-atul** [comment]
Alright could you do `npm uninstall @types/react` and try running it after that. @quaj

**Comment by quaj** [comment]
> Alright could you do `npm uninstall @types/react` and try running it after that. @quaj

Ok now worked, dont know why but running 
Could you explain?

**Comment by quaj** [comment]
Wow bundle so big
![image](https://user-images.githubusercontent.com/16853175/63276162-09cc9f00-c2cd-11e9-89fc-ed7e38881082.png)

**Comment by master-atul** [comment]
@quaj  Not really. This is your dev environment. It contains all dev node modules,assets etc.

Packaging of the app is still not ready yet. That packaged app should be around 20 - 50mb depending on the platform.

**Comment by quaj** [comment]
no only "@nodegui" folder, seems that comes from @nodegui/qode with 205MB

![image](https://user-images.githubusercontent.com/16853175/63281598-430a0c80-c2d7-11e9-9085-a0c36748492e.png)

**Comment by quaj** [comment]
here is qode info
![image](https://user-images.githubusercontent.com/16853175/63281796-b3b12900-c2d7-11e9-8a41-911bdfd3666b.png)

**Comment by master-atul** [comment]
Yes precisely, This contains all the development environment you need to run while developing.
Notice how everything works without installing Qt ? This is what does that magic.  
And you never distibute entire folder from node_modules to users. You need to bundle the required javascript using webpack or any other bundler and then copy over only the dynamically linked libraries. As I said before the distribution of the app is still WIP.
