### ISSUE TITLE
Can I put a button in top of an image?

### ISSUE THREAD

**Issue by leopku** [nodegui/react-nodegui#133]
Or something can use an image as background?
If true, how can do it?

**Comment by Solant** [comment]
you can use icon property on button component
is it enough to do the trick?

**Comment by leopku** [comment]
> you can use icon property on button component
> is it enough to do the trick?

Thanks for the reply.

Button doesn't fit my needs.
I wanna a big image as background of my app. The image should fit all of the window.

**Comment by Solant** [comment]
hmm, in this case, you can try using css for top-level component

```
style={'background-image: url(/path/to/image.png)'}
```

with some more props to handle background size, you can check reference for all supported props:
https://doc.qt.io/qt-5/stylesheet-reference.html

**Comment by leopku** [comment]
It works.
Thanks a lot!

**Comment by leopku** [comment]
`background-image` works in `nodegui` but take no effect in `react-nodegui`
I tested in react-nodegui-starter by:

### inline style like:

```css
style={'background-image: url(/Users/leo/Pictures/20150922224629_25mVM.jpeg)'}
```

### style sheet like:

```css
const styleSheet=`
  background-image: url(/Users/leo/Pictures/20150922224629_25mVM.jpeg);
`
```

All above methods did not work.

**Comment by master-atul** [comment]
Hi @leopku 

```js
import { Window, hot, View, Button } from "@nodegui/react-nodegui";
import React from "react";
import { QIcon } from "@nodegui/nodegui";
import nodeguiIcon from "../assets/nodegui.jpg";

const minSize = { width: 500, height: 520 };
const winIcon = new QIcon(nodeguiIcon);
class App extends React.Component {
  render() {
    return (
      <Window windowIcon={winIcon} windowTitle="Hello 👋🏽" minSize={minSize}>
        <View style={containerStyle}>
          <Button style={"background-color: blue;"} text="Hello"></Button>
        </View>
      </Window>
    );
  }
}

const containerStyle = `
  flex: 1; 
  background-image: url(/Users/atulr/Project/nodegui/react-nodegui-starter/assets/nodegui.jpg)
`;

export default hot(App);

```

This is the code I am using 

and this is the output i get:

<img width="560" alt="Screenshot 2020-02-29 at 10 56 00" src="https://user-images.githubusercontent.com/4029423/75605348-40883b00-5ae2-11ea-9dcd-f60036b7eee9.png">

**Comment by master-atul** [comment]
Can you post the link to a repo where I can see the issue ? @leopku

**Comment by leopku** [comment]
Magic.
After fixing https://github.com/nodegui/react-nodegui-starter/issues/89, It works now.
Thank you @master-atul and @Solant .

**Comment by leopku** [comment]
It not changed after change url(...) to a new background.
See #150, plz.
