### ISSUE TITLE
How to render HTML STYLE

### ISSUE THREAD

**Issue by Grewer** [nodegui/react-nodegui#134]
```
<View styleSheet={containerStyle}>
   <Text  id="text">{this.state.text}</Text>
</View>
```
`text: <li>hello</li>`

```
const containerStyle = `
  #text  li{
    color:'red';
   }

   LI{
     color:red;
   }
   
   UL{
     color:red;
   }
`
```
None of the above code works

If can, that's best

**Comment by master-atul** [comment]
Hi @Grewer 
Sorry for the late reply

but you seem to be mixing rich text parts with the widget parts.

In order to style the richtext you ll need to specify the styles inside it since its scoped.

So your example would look like this:

```jsx
 <View styleSheet={containerStyle}>
     <Text id="text">{`<li style=${containerStyle}>hello</li>`}</Text>
  </View>


const containerStyle = `
    color:'red';
`;
```

**Comment by master-atul** [comment]
Closing this issue.
