### ISSUE TITLE
How to use Image correctly

### ISSUE THREAD

**Issue by Grewer** [nodegui/react-nodegui#135]
# If reference the image in react
```
import testPng from './static/text.png'

<Image src={testPng}/>
```

console:
```
QPixmap::scaled: Pixmap is a null pixmap
```

**Okay it doesn't work**

# If I use resolve to reference the image

```
const imageUrl = `${path.resolve(__dirname, `./static/text.png`)}`;

<Image src={imageUrl}/>
```

**When I was debugging it was successful**

But when I pack:
```
webpack -p && nodegui-packer --pack ./dist
```

the image has not been webpacked and is not packed into dist

Image doesn't show up after I open the app

**Comment by Grewer** [comment]
If I combine these two cases, it is ok, but I cannot know the address after packaging.
```
import testPng from './static/text.png'

const imageUrl = path.resolve(__dirname, `../dist`, testPng)

console.log(imageUrl)
```

**Comment by master-atul** [comment]
Hi @Grewer 

Looks like a webpack issue. Can you reverse the value of __filename and ___dirname in webpack config?

**Comment by Grewer** [comment]
my project clone from [https://github.com/nodegui/react-nodegui-starter](https://github.com/nodegui/react-nodegui-starter)

webpack.config has not changed

@master-atul

**Comment by Grewer** [comment]
```
<Text>{`${path.resolve(__dirname).toString()}`}
```
after packing:

print:
```
/src
```

**Comment by master-atul** [comment]
Have you changed to   
```
__dirname: false,
 __filename: false
```
?

**Comment by Grewer** [comment]
ohh
it succeeded

Although successful, it is still so laborious to use

**Comment by Grewer** [comment]
Thank you

**Comment by master-atul** [comment]
> Although successful, it is still so laborious to use

Could you help me in understanding why you feel so ? 
I want to make it as easy as possible. @Grewer

**Comment by Grewer** [comment]
Compare the use of images in React
```
import testPng from './static/text.png'

<Image src={testPng}/>
```
Now to quote the picture in the project, this sentence is needed:

```
const imageUrl = path.resolve(__dirname, `../dist`, testPng)
```

can extract a method

there is also the need to change here when you want to change the `/dist` path

Although I mean laborious, it is also compared with React, which is actually okay.

**Comment by Solant** [comment]
@Grewer I did some changes to file-loader in react starter, so now you should be able to import images just like in react

https://github.com/nodegui/react-nodegui-starter/blob/master/webpack.config.js#L34

for already created project you can do the same change with `publicPath: 'dist'` and no more path.resolves

**Comment by master-atul** [comment]
@all-contributors add @Solant for code

Thank for fixing this issue 
Closing this

**Comment by Grewer** [comment]
Unfortunately this modification cannot be referenced after build

Because the reference is a relative reference, and the picture can only be referenced by absolute reference after packaging, the path in front of the referenced picture must be the path of the application plus the path of the picture resource.

@master-atul  @Solant

**Comment by Solant** [comment]
@Grewer just checked on packed windows version, Image with relative path to `qode` executable should work fine:
![image](https://user-images.githubusercontent.com/5971578/74608494-92988c00-50f2-11ea-903d-677a4fcf4356.png)

What system do you use?

**Comment by Grewer** [comment]
My system is macOS

**Comment by Grewer** [comment]
@Solant

**Comment by Grewer** [comment]
Is your usage like this:

```
import testPng from './static/text.png'

<Image src={testPng}/>
```

and  build:

```
"build": "webpack -p && nodegui-packer --pack ./dist",
```

**Comment by Solant** [comment]
@Grewer yes, but asset path is `assets` instead of static
btw, are you sure that you are referencing the right file?
>text.png
maybe you are trying to use a different file instead?

Checked this also on linux, works perfectly fine with packed version: https://github.com/Solant/polygon-launcher you can try building this project and checking it out

**Comment by Grewer** [comment]
I will try it tomorrow

**Comment by Grewer** [comment]
whether it is `static` or `assets`, the files will be in `dist` after build

I downloaded your project, after packaging, the same picture cannot be displayed
<img width="419" alt="截屏2020-02-17下午12 29 06" src="https://user-images.githubusercontent.com/21995246/74623833-1bf69f80-5181-11ea-9c87-615c20df8518.png">

**Comment by Grewer** [comment]
I created a component that wraps an Image
```
import path from 'path'
import { Image } from '@nodegui/react-nodegui'
import { ImageProps } from '@nodegui/react-nodegui/dist/components/Image/RNImage'
import React from 'react'

function WrapImage(props: ImageProps) {
  const { src = '', ...rest } = props
  const _src = path.resolve(__dirname, '../', src)
  return <Image src={_src} {...rest}/>
}

export default WrapImage
```
It runs normally in dev and build. If you can add these logics and wrap them in` Image`, it will work.
@Solant  @master-atul

**Comment by Solant** [comment]
@Grewer hmm, looks like macOS is loading stuff differently from linux and windows

>const _src = path.resolve(__dirname, '../', src)

I doubt that it will do the trick properly, as it requires specific config of both loader and runtime

Also it looks like this is applied to all assets (images, icons, fonts and so on), so it can't be fixed properly with one single image wrapper, probably some macOS specific magic for loader is required there. I'll take a look how it can be fixed

@master-atul any ideas why macOS logic differ from windows and linux?

**Comment by master-atul** [comment]
Hi @Solant  and @Grewer 
This is because the current working directory for macos is something different.
I am currently working on Qode v2.0 which might need a bit of changes in the packer as well. 
So I ll fix it up in packer alongside it. ETA: this weekend for now. But lets see if I can fix it before that. 
Thanks for looking into this @Solant

**Comment by master-atul** [comment]
Alright! I manage to fix this issue,
This will be fixed in the next packer release.

But if you would like to fix it in your current setup.

After  `npx nodegui-packer --init MyApp`

Change the contents of
`deploy/darwin/MyApp.app/Contents/MacOs/qode.json`  to
```json
{
  "distPath": "../Resources/"
}
```

Add a new file at `deploy/darwin/MyApp.app/Contents/Resources/index.js` with the contents
```js
const path = require("path");
// Fix so that macos resources are found correctly
// since webpack will bundle them such that the expected path is /dist from cwd
process.chdir(path.resolve(path.dirname(process.execPath), "..", "Resources"));
// Now start loading the actual bundle
require("./dist");

```

Now do `npx nodegui-packer --pack ./dist`

And the assets paths should be resolved correctly!
