### ISSUE TITLE
How to clear cache? Related to #133

### ISSUE THREAD

**Issue by leopku** [nodegui/react-nodegui#150]
In #133 , I can not change background image.
And today after starting project, it take effect.
But after I changing background image to new one, background image still stayed in the old one.

Is there something like cache? How can I clear it and make new background image works?

**Comment by Solant** [comment]
make sure you run both `npm run dev` AND `npm run start` at the same time
as js bundle is generated by webpack with `npm run dev`, and `npm run start`  just launches qode with generated js bundle

**Comment by leopku** [comment]
@Solant Got it.

Thanks.
