### ISSUE TITLE
hot file remove

### ISSUE THREAD

**Issue by Grewer** [nodegui/react-nodegui#159]
This often happens during development
<img width="249" alt="截屏2020-03-07上午12 14 45" src="https://user-images.githubusercontent.com/21995246/76101012-a9067900-6008-11ea-9ab9-23e0a6d68b04.png">
So I hope to be able to delete these troublesome files
It only needs to be in the `src/development/hot-reload.ts` file. When hot is first enabled, clean up the dist file.

**Comment by Solant** [comment]
you can try using a plugin like https://github.com/johnagan/clean-webpack-plugin , so dist folder will be cleaned on each `npm run dev`

**Comment by Grewer** [comment]
Of course, I can solve it myself in dev, but I mean, it is better to use it out of the box instead of configuring it by myself.

**Comment by Solant** [comment]
makes sense
anyway, it should be done in https://github.com/nodegui/react-nodegui-starter as react-nodegui doesn't have any clue about webpack's hot-reload

can you move or reopen this issue to starter repo? I'll take a look at this one there

**Comment by master-atul** [comment]
I just added this to the starter :) 

Closing this issue now. Thanks @Solant for responding and helping out!
