### ISSUE TITLE
[question] How to get value from LineEdit?

### ISSUE THREAD

**Issue by cvl** [nodegui/react-nodegui#178]
e.g. <LineEdit text={dtext}></LineEdit> 

the variable dtext is not updated, ever.

**Comment by cvl** [comment]
I think I found one way, is this correct?

var textValue: string

    const textChanged = async (val: string): Promise<void> => {
        textValue = val
    }

....
<LineEdit 
                on={{ textChanged: textChanged }}
..

**Comment by master-atul** [comment]
Yes, this is correct @cvl
