### ISSUE TITLE
It is possible to integrate Fluid (QML modules)

### ISSUE THREAD

**Issue by Tijawk** [nodegui/react-nodegui#183]
Is it possible to integrate external Qt components? I came across "Fluid" which offers Qt components with a modern design.

https://liri.io/docs/sdk/fluid/develop/index.html

I have no experience with Qt, so if someone can guide me step by step to integrate (if possible). Thanks

**Comment by master-atul** [comment]
Sorry, I dont think this can be used with NodeGui.
