### ISSUE TITLE
Error: Cannot read property 'ok' of undefined in react-sound

### ISSUE THREAD

**Issue by abhigk** [nodegui/react-nodegui#194]
Hi
I am not able to use react-sound with react-nodegui. React-sound is working fine with creat-react-app. 

My code:
![Screen Shot 2020-04-16 at 4 19 10 pm](https://user-images.githubusercontent.com/9884510/79421623-8e0f2780-7ffe-11ea-9561-df32ef542efc.png)

Error:
![Screen Shot 2020-04-16 at 4 19 01 pm](https://user-images.githubusercontent.com/9884510/79421657-9ff0ca80-7ffe-11ea-815c-b49da927ec6a.png)

Thanks

**Comment by master-atul** [comment]
React sound is based on soundmanager2, whivh uses HTML5 audio api. This means react sound needs a browser to run. 

NodeGui is a native platform and doesnt run inside a browser. Hence it doesnt support sny browser based apis. 

You ll need to find a nodejs based sound library to achieve what you are looling for

**Comment by abhigk** [comment]
How would I use a node library in react-nodegui?

**Comment by master-atul** [comment]
react nodegui is just a regular nodejs application. You can think of react nodegui as a library to nodejs. So any other nodejs library can be used along with it.

**Comment by abhigk** [comment]
Thank you for quick explanation 😊
