### ISSUE TITLE
Native modules support for OS X

### ISSUE THREAD

**Issue by s-kris** [nodegui/react-nodegui#198]
Does native modules work in OS X context here?  (ref: https://reactnative.dev/docs/native-modules-ios)

**Comment by master-atul** [comment]
Hi @s-kris  I am not really sure what you mean here? 

Do you mean to ask if react-nodegui works with ios ?

**Comment by s-kris** [comment]
Sorry, I meant, can we use native code(OS X APIs) in react-nodegui ?
For example, in react-native we can use native modules concept to use ios-specific APIs in react-native app.

**Comment by master-atul** [comment]
Hi, yes you can 

You can do this by creating a nodegui plugin or even a regular nodejs addon.

An example of nodegui plugin with native code can be found here:  https://github.com/nodegui/nodegui-plugin-example

And an example of a regular nodejs addon used along with nodegui can be found here:   https://github.com/nodegui/os-utils

**Comment by s-kris** [comment]
thank you @master-atul! My bad, I missed the native modules section the last time checked react-nodegui docs. Will keep an eye on this space: https://react.nodegui.org/docs/guides/custom-nodegui-native-plugin
