### ISSUE TITLE
Image from URL produce null pixmap

### ISSUE THREAD

**Issue by nsebhastian** [nodegui/react-nodegui#203]
Hello, I'm currently trying to render an image from URL with no success. I even tried the Image rendering from the docs:

```
import React from "react";
import { Renderer, Image, Window } from "@nodegui/react-nodegui";
const App = () => {
  return (
    <Window>
      <Image src="https://docs.nodegui.org/img/logo-circle.png" />
    </Window>
  );
};
Renderer.render(<App />);
```

But it just opened a blank window with a message in the console:

`QPixmap::scaled: Pixmap is a null pixmap`

I'm currently using Windows 10 and Node v12.16.3. I'm using TypeScript for compiling before running `qode`.

Here is my `package.json` file:
```
{
  "name": "react-nodegui-hello-world",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "scripts": {
    "start": "tsc && qode dist/index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nodegui/nodegui": "^0.1.3",
    "@nodegui/react-nodegui": "^0.1.1",
    "react": "^16.9.0"
  },
  "devDependencies": {
    "@types/react": "^16.9.2",
    "@types/react-reconciler": "^0.18.0",
    "typescript": "^3.5.3"
  }
}
```

and my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "jsx": "react",
    "strict": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "outDir": "./dist"
  },
  "include": ["**/*"]
}
```

Can someone help me out? Thanks!

**Comment by master-atul** [comment]
Hi @nsebhastian 
Do you also get the same when you try to load from a local file ?

**Comment by master-atul** [comment]
The example seems to work fine on a mac

**Comment by master-atul** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/4029423/81265918-2a4bad80-9044-11ea-93f4-1710c779362c.png">

**Comment by master-atul** [comment]
I can take a look at it on windows and linux later today.

**Comment by nsebhastian** [comment]
Hi @master-atul it turns out the dependencies are installing older versions of nodegui packages. I have downloaded the latest version and it works fine now. Thanks for your reply :)
