### ISSUE TITLE
Question: Making Views Scrollable

### ISSUE THREAD

**Issue by illBeRoy** [nodegui/react-nodegui#22]
Hello!

First of all, I've just run into nodegui a couple of days ago and it seems absolutely amazing. While not the first react desktop solution out there, it sure does deliver simplicity of set up and ease of use. Kudos.

I've a question regarding scrolling: I'm trying to figure out how I can make certain views scrollable. `overflow: scroll` has no effect, and I'm not sure whether or not I should use `QScrollArea`. Help would be much appreciated :)

Also, if you need help with the documentation - I've a knack for writing docs. With a little bit of guidance I'd love to contribute back to the readme.

Cheers!

**Comment by master-atul** [comment]
Hi @illBeRoy  
Yes It would be amazing if you can help out in anyway.  I am always ready to help out. I think we can just use this issue as a discussion channel in case you need any help.  

Yes overflow:scroll doesnt exist in Qt CSS
these are the supported properties: https://doc.qt.io/archives/qt-4.8/stylesheet-reference.html#list-of-properties

For scrolling you would need to use QScrollArea which currently exists on NodeGUI but not in React NodeGUI.  We need to export a React version of it. It should be available soon though once I finish work on app packaging or other contributors chime in to help out.

**Comment by illBeRoy** [comment]
Thanks for the quick response! I'll fork the `react-nodegui` repo and try to get a `ScrollArea` component done :)

**Comment by master-atul** [comment]
This is now available in v0.1.9 of react-nodegui and nodegui.

Hence closing this issue.  :)
