### ISSUE TITLE
App crash when loading a lot of images

### ISSUE THREAD

**Issue by kristijanhusak** [nodegui/react-nodegui#231]
**Describe the bug**
I'm calling github api and printing out the results, and for each result there is an avatar of the repo owner. After several calls and renders app crashes without any error. When I do not use `<Image>` everything works fine.

**To Reproduce**
It requires some setup, at least for my case, but maybe it is reproducible in some other way. Here are the basic steps:
1. Fetch results from github (i'm using axios and calling `https://api.github.com/search/repositories?q={term}&sort=stars&order=desc`), where `{term}` is value from input.

2. Print some repo details. Here's jsx i'm using:
```jsx
  const list = items.map((item: any, index: number) => (
    <View key={`github_${item.name}_${index}`} id="github-item">
      <View id="github-image">
        <Image src={item.avatar} id="#github-image-item" maxSize={{ width: 50, height: 50 }} />
      </View>
      <View id="github-content">
        <Text>{item.owner}</Text>
        <Text>{item.name}</Text>
        <Text>{item.description}</Text>
      </View>
    </View>
  ))

  return (
    <View styleSheet={styleSheet}>{list}</View>
  )

```
3. Change input value several times, wait each time data to print
4. Should crash after several times

If this is not enough for figuring it out, I can spend some time setting up a demo project, but i'm not sure how that will help since there is no any errors when it crashes.

**Expected behavior**
Not to crash

**Additional context**
My assumption is that it has a memory leak somewhere, which should be either handled by QT, nodegui or a developer. I didn't find anything that I should do to make it free up memory.
As noted above, when I remove `<Image>`, text part properly works and do not crash.

**Comment by agg23** [comment]
How many items are you displaying? It appears the API returns 30 results by default. Is that the count you're using?

You don't get any error message at all? What OS are you using?

What happens if you don't use the `Image` component to do the HTTP fetching?

**Comment by kristijanhusak** [comment]
Yeah, 30 results.

No, app just exits without anything in the console.
Im using Manjaro Linux

When i don't use `Image`, everything works fine.

**Comment by kristijanhusak** [comment]
Here's a gif how it works for me both with and without images.

![mydemo](https://user-images.githubusercontent.com/1782860/84638723-a795f800-aef7-11ea-8851-ffb9b70f7b0a.gif)

**Comment by a7ul** [comment]
Does it happen in the production build aswell ?

**Comment by kristijanhusak** [comment]
@a7ul yeah, i packed it up and tried. Same thing.

**Comment by kristijanhusak** [comment]
@a7ul It looks like i have some different issue, I'm just not sure why exactly removing images fixes it. Wait on this for now until i figure it out.

**Comment by kristijanhusak** [comment]
I spent some time debugging it. Turns out something around the state is causing the issue.
I made a demo project so you can look into it yourself: https://github.com/kristijanhusak/react-nodegui-test-project

Basically, when this line is commented out https://github.com/kristijanhusak/react-nodegui-test-project/blob/master/src/app.tsx#L23, there are no crashes.

Also, same as in few comments above, removing the image tag https://github.com/kristijanhusak/react-nodegui-test-project/blob/master/src/github.tsx#L16 and leaving the first line uncommented also makes it work.

My assumption is that changing of state somehow interrupts things between renders, and causes the crash.

Maybe i'm not using these react hooks properly, since i don't have much experience with them (been using older react without hooks).

**Comment by kristijanhusak** [comment]
I made it work with `useReducer` without any issues. I guess my code was causing some issues. Feel free to close this if you think there's anything to fix.

**Comment by a7ul** [comment]
Thanks for reporting back @kristijanhusak 
closing this issue for now.
