### ISSUE TITLE
Access underlying QWidget for Painting, etc.

### ISSUE THREAD

**Issue by swittk** [nodegui/react-nodegui#235]
Hi there. I've been trying out simple programs with React NodeGUI. Works well, no complaints yet :) Thing is, I'm starting to write a graphing component. With Pure NodeGUI, I see we have the QPainter, which can draw into components using the callback addEventListener(WidgetEventTypes.Paint, <draw function>). However, with React-NodeGUI, I couldn't really access the underlying QWidget from the View component.

Right now I'm tinkering with Refs. Using a callback ref acquiring function on <View>, I found that the underlying Refs are RNView objects, and has a property of "native" which shows up as QWidget in node console, however, the QWidget object itself has no properties? Also, there's no function addEventListener to be called (calling addEventListener simply says is not a function)

So I guess what I want to happen is an ability to either access the underlying QWidget and do stuff with it, or an alternative; a new Component to paint in.

**Comment by a7ul** [comment]
So, RNView inherits from QWidget which basically means you can treat RNView as QWidget from NodeGui. I hope that helps. @swittk

**Comment by swittk** [comment]
Oh hey, it works now :)
Thanks a lot. I'll be closing this issue then.

Maybe this could be added into the documentation. Maybe in an "advanced usage", or "accessing Qt NodeGUI objects" section or something.
