### ISSUE TITLE
How to text-align center <Text/>?

### ISSUE THREAD

**Issue by jabza** [nodegui/react-nodegui#258]
Hi,

I'm using the Text component, but it looks like QT css doesn't support `text-align` - is there a way (other than parent centering via flex) to justify text. Currently it always aligned to the left.

Any tips would be much appreciated :)

Thank you

**Comment by a7ul** [comment]
Hey @jabza  You can use

```
qproperty-alignment: AlignCenter;
``` 
in your css stylesheet.

**Comment by jabza** [comment]
> Hey @jabza You can use
> 
> ```
> qproperty-alignment: AlignCenter;
> ```
> 
> in your label css stylesheet.

Perfect! Cheers for the quick reply.

This is by far the best (and fastest) experience I've had creating a cross-platform GUI, utilizing React without the bloat of electron.

Thanks for creating this awesome framework :)

**Comment by funcelot** [comment]
> Hey @jabza You can use
> 
> ```
> qproperty-alignment: AlignCenter;
> ```
> 
> in your label css stylesheet.

Does not work on Qt6 on Windows 10

Works as 

```

        text_widget = QLabel(_placeholder)
        text_widget.setWordWrap(True)
        text_widget.setAlignment(Qt.AlignCenter)
        button = QPushButton("Something")

```
