### ISSUE TITLE
How to compile react-nodegui for production use

### ISSUE THREAD

**Issue by Alkanores** [nodegui/react-nodegui#271]
After "npm run build" I can't get .exe file (or another executable file)

**Comment by a7ul** [comment]
Please use this: https://github.com/nodegui/packer

**Comment by Alkanores** [comment]
@a7ul  reopening issue, nodegui/packer don't work (and repository dead, last commit - 17 april)

(node:3860) UnhandledPromiseRejectionWarning: child process exited with code 1
(node:3860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Alkanores** [comment]
@a7ul  nodegui/packer don't create .exe

![image](https://user-images.githubusercontent.com/49155506/92999154-8315e000-f527-11ea-8717-21d2f3cd2d47.png)

![image](https://user-images.githubusercontent.com/49155506/92999104-07b42e80-f527-11ea-9128-be1204cdc981.png)

**Comment by Alkanores** [comment]
@a7ul any update?
