### ISSUE TITLE
Auto Translation of normal CSS into qproperty feature request

### ISSUE THREAD

**Issue by nateshmbhat** [nodegui/react-nodegui#28]
The styling should feel more natural to the user just as in using with react and other web development frameworks . so it would be very helpful to add translation of many unsupported css properties into corresponding Qt css properties.

**Comment by master-atul** [comment]
Hi @nateshmbhat 
Could you give an example of what you are suggesting? 

Currently you dont need to use qproperty- for any flex properties as they are taken care of by an autoprefixer already https://github.com/nodegui/postcss-nodegui-autoprefixer
