### ISSUE TITLE
Cant do functions with created push button

### ISSUE THREAD

**Issue by terryyoung22** [nodegui/react-nodegui#300]
**Is your feature request related to a problem? Please describe.**
I am trying to find clear documentation on how to execute a command locally 

**Describe the solution you'd like**
Trying to build an automation desktop app for my devs and not sure how to link my created button to execute a command, do more then console.log

**Describe alternatives you've considered**
not much, didnt know if it would be written in another langues than what is on the TSX or what

**Additional context**
Looking for documentation or examples of how the buttons work to interact with the MacOS on a directory level for certain task

**Comment by a7ul** [comment]
Hey @terryyoung22 

Can you use the nodejs's inbuilt  child_process exec to execute your script ? 

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by terryyoung22** [comment]
Hey @a7ul I will for sure try and take a look. I wasnt sure if that was an acceptable call within the react-nodegui framework. I will try it, thank you.

**Comment by a7ul** [comment]
react-nodegui is just a library that works on top of NodeJs. Hence you can call any nodejs api.  
Since this is not an issue with react nodegui I am going to close this issue.
