### ISSUE TITLE
[Webpack] Conflict: Multiple assets emit different content to the same filename nodegui_core.node

### ISSUE THREAD

**Issue by jabza** [nodegui/react-nodegui#328]
**Describe the bug**
Seeing a warning from Webpack about two 'assets' 'emitting different content' to nodegui_core.node.

My project uses:
"@nodegui/nodegui": "^0.27.0",
"@nodegui/react-nodegui": "^0.10.0"

Removing nodegui doesn't appear to remove the warning.

I believe this warning started when I upgraded from nodegui@0.24.0

Everything appears to work, but a possible cause for concern?

**Comment by a7ul** [comment]
you could remove nodegui from your dependencies since react-nodegui has it under its dependencies. 

It should be okay actually. But to double check can you print `npm ls @nodegui/nodegui` and see if two different node modules are installing it.

**Comment by jabza** [comment]
> you could remove nodegui from your dependencies since react-nodegui has it under its dependencies.
> 
> It should be okay actually. But to double check can you print `npm ls @nodegui/nodegui` and see if two different node modules are installing it.

I have ran `npm ls @nodegui/nodegui` which yields:

```
+-- @nodegui/nodegui@0.25.0 
`-- @nodegui/react-nodegui@0.9.0
  `-- @nodegui/nodegui@0.25.0 
```

I am required to include nodegui directly in my react-nodegui in order to work with the primitive Q classes nodegui provides.

What is odd is that removing nodegui and using only react-nodegui, I still get the webpack warning.
