### ISSUE TITLE
npm start doesnt work ends with Error

### ISSUE THREAD

**Issue by khanobd** [nodegui/react-nodegui#35]
![nodegui](https://user-images.githubusercontent.com/32788126/65655706-b6234300-e03a-11e9-9008-c4c90d47ec56.jpg)
on  npm start  get below error 

error in index.ts 
Module not found : Error  : cant resolve  @nodegui/nodegui  in c/user/lenovo/node-sarter/src
npm ERR! nodegui-starter@1.0.0 start .......

 - OS: windows 7
 - NodeGUI version    v 12.10
 - React NodeGUI version 
npm   6.10.3

Kindly suggest

**Comment by master-atul** [comment]
Hi @khanobd  
Could you try deleteing you node_modules folder and do an npm install again ?

Also could you post the logs of your npm install aswell ?

**Comment by khanobd** [comment]
Hi @master-atul  
Please find logs attached .
delete my nodegui-starter 
and run below commands again   
----------------------------------------- 
# Clone the repository
$ git clone https://github.com/nodegui/nodegui-starter
# Go into the repository
$ cd nodegui-starter
# Install dependencies
$ npm install
# Run the app
$ npm start
----------------------------------------- 
please find logs attached 
[2019-09-27T13_24_32_732Z-debug.log](https://github.com/nodegui/react-nodegui/files/3662922/2019-09-27T13_24_32_732Z-debug.log)
[2019-09-27T13_24_40_535Z-debug.log](https://github.com/nodegui/react-nodegui/files/3662923/2019-09-27T13_24_40_535Z-debug.log)

**Comment by khanobd** [comment]
sorry for bold and fonts

**Comment by khanobd** [comment]
[2019-10-01T12_47_24_654Z-debug.log](https://github.com/nodegui/react-nodegui/files/3676223/2019-10-01T12_47_24_654Z-debug.log)
[Uploading 2019-10-01T12_47_34_370Z-debug.log…]()

**Comment by khanobd** [comment]
kindly suggest

**Comment by master-atul** [comment]
Hi @khanobd 

I was a bit busy last few days. Have you installed all the requirements mentioned here: 
https://docs.nodegui.org/docs/guides/getting-started ?

Looks like the build doesnt start on your system.

**Comment by khanobd** [comment]
Yes and tried on other system too but no success

**Comment by khanobd** [comment]
npm start  comes up with error always

**Comment by master-atul** [comment]
Hi, I believe it might be possible that we have issues with Windows7. 
But anyway could you install https://visualstudio.microsoft.com/visual-cpp-build-tools/
and give it a try again?  @khanobd

**Comment by khanobd** [comment]
Ok I will and update

**Comment by khanobd** [comment]
Hi Atul 

Install build but no success

**Comment by khanobd** [comment]
Hi @master-atul 

Done with configuration on windows 10 ... it was actually some version and upgrades
Need to configure on linux and done whole setup " npm install" successfull just atlast while " npm start " 
get below  error 
"qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
"
Reinstall it but stuck again .... Kindly suggest

**Comment by master-atul** [comment]
Nice! 
Okay so some linux distributions have this issue. (Ubuntu/Debian works fine). To solve this you can install qt on your linux system (only needed for development).

**Comment by khanobd** [comment]
@master-atul   QT installed but still comes up with this error ...Kindly suggest

**Comment by master-atul** [comment]
Okay once you have done that. 
Can you try setting an environment variable QT_INSTALL_DIR=/Users/<path to qt>/5.13.0/clang_64
before running the npm run start command @khanobd

**Comment by khanobd** [comment]
Hi @master-atul 
Done with mentioned above steps   still geting below message 
=============
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
===================== 
Kindly suggest

**Comment by khanobd** [comment]
One more issue facing here with
eps@ubuntu:~$ node -v
v10.16.3
eps@ubuntu:~$ nodejs -v
v4.2.6
eps@ubuntu:~$

even after purge and reinstalling 12x on restart its again V10.6 
tried a lot but no success If can please suggest too may be this too issue create problem 
using ubuntu 16.4

**Comment by master-atul** [comment]
Could you install node js using something like nvm : https://github.com/nvm-sh/nvm
This should allow you to easily switch node versions.

**Comment by khanobd** [comment]
eps@ubuntu:~$ node -v
v10.16.3
eps@ubuntu:~$ nvm ls
->     v10.16.3
        v12.4.0
       v12.11.1
         system
default -> v10.16.3
node -> stable (-> v12.11.1) (default)
stable -> 12.11 (-> v12.11.1) (default)
eps@ubuntu:~$ nvm use system
Now using system version of node: v12.4.0 (npm v6.9.0)
eps@ubuntu:~$ nvm run system --v12.4.0
Running node system (npm v6.9.0)	
eps@ubuntu:~$ node -v
v12.4.0
---- 
its already install and default is default -> v10.16.3  ... I need to swith ...Done

**Comment by khanobd** [comment]
Running below mentioned steps 
rm -rf node_modules
QT_INSTALL_DIR=/Users/path/to/qt/5.13.0/clang_64 npm install
and
QT_INSTALL_DIR=/Users/path/to/qt/5.13.0/clang_64 npm start

Still Come still with error 

qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by master-atul** [comment]
could you post the actual command you used instead of
``` QT_INSTALL_DIR=/Users/path/to/qt/5.13.0/clang_64 npm install``` ?

**Comment by khanobd** [comment]
@master-atul remove  modules and run below commands to install and run as mentioned by you few days back 

rm -rf node_modules
QT_INSTALL_DIR=/Users/path/to/qt/5.13.0/clang_64 npm install
and
QT_INSTALL_DIR=/Users/path/to/qt/5.13.0/clang_64 npm start

**Comment by master-atul** [comment]
Yes @khanobd 

but did I want to know what path you specified in QT_INSTALL_DIR

**Comment by khanobd** [comment]
/home/eps/nodegui-starter

**Comment by master-atul** [comment]
QT_INSTALL_DIR should bevthe path to ur qt installation folder not the one u specified above

**Comment by khanobd** [comment]
there run the mentioned command 
and path shows is 
/home/eps/nodegui-starter/node_modules/@nodegui/qode/dist/1.0.5/include/QtCore/5.13.0

**Comment by khanobd** [comment]
at this path /home/eps/nodegui-starter
run command QT_INSTALL_DIR=/Users/path/to/qt/5.13.0/clang_64 npm install
and now path shows is 
/home/eps/nodegui-starter/node_modules/@nodegui/qode/dist/1.0.5/include/QtCore/5.13.0

is it somewhere have done a miss ?

**Comment by master-atul** [comment]
ok @khanobd could you paste the actual location where you have installed Qt on your system?

**Comment by khanobd** [comment]
eps@ubuntu:~/nodegui-starter$ pwd
/home/eps/nodegui-starter
eps@ubuntu:~/nodegui-starter$

**Comment by khanobd** [comment]
eps@ubuntu:/opt$ whereis qt5
qt5: /usr/share/qt5
eps@ubuntu:/opt$

**Comment by master-atul** [comment]
yes so you should be using  QT_INSTALL_DIR=/usr/share/qt5/5.13.0/clang_64 npm install

Please do check if those folders exist for you in the location 
Check if this path exists (/usr/share/qt5/5.13.0/clang_64 ) or modify accordingly

**Comment by khanobd** [comment]
Yes its not there 
eps@ubuntu:/usr/share/qt5$ cd 5.13.0
-bash: cd: 5.13.0: No such file or directory
eps@ubuntu:/usr/share/qt5$ ls -a
.  ..  doc  phrasebooks  translations
eps@ubuntu:/usr/share/qt5$

**Comment by khanobd** [comment]
eps@ubuntu:~/nodegui-starter$rm -rf node_modules
eps@ubuntu:~/nodegui-starter$QT_INSTALL_DIR=/usr/share/qt5/5.13.0/clang_64 npm install 
eps@ubuntu:~/nodegui-starter$QT_INSTALL_DIR=/usr/share/qt5/5.13.0/clang_64 npm start  
eps@ubuntu:~/nodegui-starter$ pwd
/home/eps/nodegui-starter

Is is what did right ?
no success :(  
same error
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.


Extremly sorry to trouble @master-atul

**Comment by khanobd** [comment]
Plugin folder was empty and yes some path issue ... purge QT 
Install again with 

sudo apt-get -y update
sudo apt-get -y install build-essential libgl1-mesa-dev libassimp-dev libfontconfig1 libdbus-1-3 wget
sudo wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run
sudo chmod +x qt-opensource-linux-x64-5.9.1.run
./qt-opensource-linux-x64-5.9.1.run

But here  while  running ./qt-opensource-linux-x64-5.9.1.run
 get below error

root@ubuntu:~# ./qt-opensource-linux-x64-5.9.1.run
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QXcbConnection: Could not connect to display

Suggest please

**Comment by master-atul** [comment]
This shouldnt happen in the latest version of react-nodegui.
Closing this issue
