### ISSUE TITLE
Debugging code process page 404

### ISSUE THREAD

**Issue by Suniron** [nodegui/react-nodegui#36]
**Describe the bug**
The documentation page for debugging process is not found.

**To Reproduce**
1. Follow ink [https://docs.nodegui.org/#/tutorial/debugging-qode-process]
2. See error

**Comment by master-atul** [comment]
Hmm, thats weird. 
But here is the actual working link : https://docs.nodegui.org/#/tutorial/debugging-app?id=debugging-qode-process

We are also currently working on a shiny new documentation website that should fix all of the broken links as well. The new documentation website should be much easier to work and should be available very soon. Thanks for reporting anyway! 👍

**Comment by Suniron** [comment]
OK thanks!

I'm really impatient to read the React Documentation for nodegui :-D!
