### ISSUE TITLE
QPixmap::scaled: Pixmap is a null pixmap

### ISSUE THREAD

**Issue by herlarb** [nodegui/react-nodegui#37]
**Describe the bug**
When I attempt to load an image from a remote repository I get an error message "QPixmap::scaled: Pixmap is a null pixmap"
**To Reproduce**
```
import * as React from 'react';
import {Image, View , Window, Renderer } from '@nodegui/react-nodegui';
import { AspectRatioMode } from '@nodegui/nodegui';

const minSize = {width:414, height:736};


const App : React.FC = () =>(
     <Window minSize={minSize}>
          <View  style="flex:1">
              <Image 
            aspectRatioMode={AspectRatioMode.KeepAspectRatio}
            src={'https://randomuser.me/api/portraits/thumb/men/1.jpg'}
               />
         </View>
      </Window>
) 

Renderer.render(<App />)
```

**Expected behavior**
I expect that I am able to load Images from remote URLs

**Desktop (please complete the following information):**
 - OS:  Windows
 - NodeGUI version: 0.1.9 
 - React NodeGUI version : 0.1.9
 - OS Version Windows 10

**Additional context**
I used the react-nodegui starter template

**Comment by talentlessguy** [comment]
You should import images like this:

```ts
import img from './path'
import { resolve } from 'path'

// blah blah

<Image src={resolve(__dirname, img)} />
```

**Comment by master-atul** [comment]
https://github.com/nodegui/react-nodegui/pull/81 This pr resolve this issue

**Comment by master-atul** [comment]
Will be available in next release

**Comment by master-atul** [comment]
Released in https://github.com/nodegui/react-nodegui/releases/tag/v0.3.1
