### ISSUE TITLE
Spaces not allowed in project directory

### ISSUE THREAD

**Issue by adamsoutar** [nodegui/react-nodegui#39]
**Describe the bug**

Not sure this is the right repo to file this in, but when performing `npm install` in the react-nodegui-starter, I got 
```
AssertionError: Spaces in action output filenames not supported (/Users/adam/Documents/Mac Projects/react-nodegui-starter/node_modules/@nodegui/qode/dist/1.0.5/include/QtCore)
```

**To Reproduce**

1. Create and cd to a directory path with a space in it
2. `git clone https://github.com/nodegui/react-nodegui-starter`
3. `npm i`

**Expected behavior**
Dependencies install correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/26578100/66261501-4b0a0700-e7c6-11e9-9252-9d251609639b.png)

**Desktop:**
 - OS: macOS
 - NodeGUI version: @nodegui/nodegui@0.1.9
 - React NodeGUI version: @nodegui/react-nodegui@0.1.9
 - OS Version: 10.15 Beta (19A582a)

Is there a known workaround for this (besides working in a folder without spaces, which I am doing for the moment)?

**Comment by master-atul** [comment]
Hi @adamsoutar 
Yes, this was the limitation with `node-gyp` which was the build system (default nodejs addon build system( used in nodegui@0.1.9.

In nodegui@0.2 and up we are using cmake. You could try the updated https://github.com/nodegui/react-nodegui-starter and this should go away.
