### ISSUE TITLE
how to run after build

### ISSUE THREAD

**Issue by yuu2lee4** [nodegui/react-nodegui#41]
i cant run dist after i run command `npm run build`
![image](https://user-images.githubusercontent.com/8046366/66466600-9289df00-eab5-11e9-83ce-bfb3466d8ef4.png)

**Comment by master-atul** [comment]
Hi @yuu2lee4  Seems like some dependecies did not install correctly. 
Could you try the updated https://github.com/nodegui/react-nodegui-starter 
again and let us know.

**Comment by yuu2lee4** [comment]
![image](https://user-images.githubusercontent.com/8046366/66891897-c8324900-f01c-11e9-9558-faab0656f25b.png)
so i need get a cmake for my mac?

**Comment by master-atul** [comment]
Yes the latest version requires cmake

**Comment by yuu2lee4** [comment]
![image](https://user-images.githubusercontent.com/8046366/66902320-09cdee80-f033-11e9-8a3d-c6c929ffb0f4.png)

**Comment by master-atul** [comment]
no. You are using node to run the dist
You should be using qode instead.

Inshort; Just run npm run start

**Comment by yuu2lee4** [comment]
So the app is small,but qode is very large,it will be great if qode can be installed as a independent system component
