### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by mjarmoc** [nodegui/react-nodegui#42]
**Is your feature request related to a problem? Please describe.**
Hi. Thank you for the project. It looks really great and makes me want to dig in, despite the fact I am not a react developer. I have checked the examples and my concern is that even with simple apps things are getting complex really fast. What I am missing is some kind of DOM-less router to attach/detach components based on global state.

**Describe the solution you'd like**
I would like to create components for 'app pages' with encapsulation and attach/detach them based on store property value.

**Describe alternatives you've considered**
Maybe react-router-native will do the job? If so, could you provide an example how to use it?

**Comment by herlarb** [comment]
@mjarmoc  I already asked something similar in the spectrum chat sometimes back and this was the response I got from @master-atul 

> Currently there is no navigation library in the works. I believe someone was looking to build a navigation library for react-nodegui but I can remember clearly. But nothing solid yet. Maybe you can take a look at building one if you have the time?
> So at this moment, if you want to build something it would be via a switch case 

Hope this information helps

**Comment by master-atul** [comment]
Hey @herlarb  and @mjarmoc 
React NodeGui now supports react-router :) 
You can check out the example repo here on how to use it: https://github.com/nodegui/examples/tree/master/react-nodegui/react-router-example
