### ISSUE TITLE
require("@nodegui/nodegui") in version 0.1.9

### ISSUE THREAD

**Issue by sophiehui99** [nodegui/react-nodegui#43]
in version 0.1.9,the package name is ‘react-nodegui’,but in components,you use it with 'require("@nodegui/nodegui")'.
You should reference it with ‘require("@nodegui/react-nodegui")’ or change the package name

![image](https://user-images.githubusercontent.com/18158091/66538604-c0276480-eb57-11e9-953f-47f0fa15b5d3.png)

**Comment by master-atul** [comment]
Hi @sophiehui99 
React NodeGui depends on nodegui for rendering its widgets. So RNCheckbox will need to import from nodegui/nodegui.

You can try the updated starter project here: https://github.com/nodegui/react-nodegui-starter and let us know if you still face issues.
