### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by scotteratigan** [nodegui/react-nodegui#45]
**Describe the bug**
npm install fails

**To Reproduce**
1. npm install

**Expected behavior**
npm install is expected to finish without error

**Screenshots**
Error Log:
> npm run build:addon

> @nodegui/nodegui@0.1.9 build:addon G:\react-nodegui-starter\node_modules\@nodegui\nodegui
> node-gyp -j 8 configure build

G:\react-nodegui-starter\node_modules\@nodegui\nodegui>if not defined npm_config_node_gyp (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" -j 8 configure build )  else (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" -j 8 configure build )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Admin\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "-j" "8" "configure" "build"
gyp ERR! cwd G:\react-nodegui-starter\node_modules\@nodegui\nodegui
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.1.9 build:addon: `node-gyp -j 8 configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.1.9 build:addon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-10-10T23_19_19_270Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.1.9 postinstall: `npm run build:addon`
npm ERR! Exit status 1

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64 bit using Git Bash
 - NodeGUI version: 0.1.9 ?
 - React NodeGUI version: 1.0.0

**Additional context**
None I can think of.

**Comment by master-atul** [comment]
Hi @scotteratigan  I have updated the starter project (react-nodegui-starter). Could you try again and let me know ? 
Make sure you have cmake installed.

**Comment by lovelyJason** [comment]
> Hi @scotteratigan I have updated the starter project (react-nodegui-starter). Could you try again and let me know ?
> Make sure you have cmake installed.

macos can install cmake by 'brew install cmake'.What should I do to install cmake on windows platform
