### ISSUE TITLE
ScrollArea is very difficult to use

### ISSUE THREAD

**Issue by J-Cake** [nodegui/react-nodegui#46]
More of an enhancement than a bug report, but using the `ScrollArea` isn't the easiest thing in the world. for example, I can't seem to get it to fill the parent, nor, will it render its content whatsoever.

I so far have only been ale to declare one with fixed sizes declared in pixels through CSS, but I need it to fill the parent. If not, perhaps an automatically overflowing `View` would be a better approach, something React Developers, coming from the web might be more comfortable with.

**Comment by master-atul** [comment]
Hi @J-Cake 
I have updated the starter project : react-nodegui-starter with a scrollview that fills the parent widget. I think it might be what you are looking for.

**Comment by master-atul** [comment]
There is a tiny bug where I need to assign min-width and min-height to the scrollView child at the moment.

**Comment by slidinghotdog** [comment]
@master-atul i could only get it to work setting height in pixels for the `View` inside like in the example, how do i do it if the `View` size is variable?

**Comment by master-atul** [comment]
This is now fixed in the latest version of react-nodegui.

The scrollArea now can render dynamically sized content. Checkout the latest release :) @slidinghotdog

**Comment by JulianSolros** [comment]
@a7ul where is the scrollview example? I don't see it in the starter project....

**Comment by CapitaineJSparrow** [comment]
Hello, i'm looking for the scrollview example as well

**Comment by a7ul** [comment]
https://react.nodegui.org/docs/guides/scroll-view

**Comment by academo** [comment]
Currently using

```
    "@nodegui/nodegui": "^0.44.0",
    "@nodegui/react-nodegui": "^0.13.0",
```

I can't get the scrollview to render a children on full width, it somehow forces the child to use the min width possible. I tried many combinations setting flex: 1 to the scroll area, children and so on but so far nothing.

If I were to render only the child without the scroll area, it will work all fine, but when the scroll area is added, all breaks.

**Comment by CapitaineJSparrow** [comment]
@academo I'm experimenting exactly same behavior
