### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by Regaron** [nodegui/react-nodegui#5]
How to enable hot reload?

**Comment by master-atul** [comment]
Its not yet present. But I believe you could use react-hot-reloader from dan abramov. 

But this is definetly on the cards to support.

**Comment by master-atul** [comment]
Its on the cards here: https://github.com/nodegui/nodegui/projects/1#card-25295584

Closing this issue

**Comment by agustif** [comment]
What about using nodemon or watchman when calling yarn dev or start from package.json?

Great project btw!

**Comment by master-atul** [comment]
For a temporary solution:

Live reload can be achieved by adding the following npm script:

```
"start:watch": "nodemon -e js,ts,tsx --ignore dist/ --ignore node_modules/ --exec npm start"  
```

**Comment by master-atul** [comment]
Fixed in https://github.com/nodegui/react-nodegui/pull/52

**Comment by master-atul** [comment]
Try the latest react-nodegui-starter for Hot-Reloading :)
