### ISSUE TITLE
How to remove a Window component?

### ISSUE THREAD

**Issue by slidinghotdog** [nodegui/react-nodegui#54]
Hi, im trying to use a second window to make a file/folder picker (i didn't find anything, but is there a simpler way to do it? maybe some widget, or something from the os?), but i can't figure out if theres a way to close it from the javascript side (should close according to some user input), after watching this video https://youtu.be/8jH5gaEEDv4?t=1376 , i tried this:

```
function App() {
  const [showWindow, setShowWindow] = useState(false);
  const toggleWindow = () => {
    setShowWindow(!showWindow);
  };
  return (
    <>
      <Window windowTitle="Hello 👋🏽" size={mainWindowSize}>
        <View>
          <Button text="Toggle Window" on={{ clicked: toggleWindow }}></Button>
        </View>
      </Window>
      {showWindow && (
        <Window
          windowTitle="Second Window"
          size={secondWindowSize}
        >
          <View>
            <Text>Second Window</Text>
          </View>
        </Window>
      )}
    </>
  );
}
```

but the second window doesn't close when `showWindow` is toggled to `false`, and when  it is toggled to `true`, it opens another "Second Window".

![Screenshot_2019-11-11_00-15-01](https://user-images.githubusercontent.com/33790211/68558525-6812a500-0418-11ea-8428-ad3537a8f5bd.png)

**Comment by master-atul** [comment]
Oh that looks like a bug. 

But for the time being could you use the visibility prop instead to show and hide the window ?

**Comment by slidinghotdog** [comment]
Didn't think of that, it works fine now, thanks!
