### ISSUE TITLE
How do you build binaries?

### ISSUE THREAD

**Issue by krestaino** [nodegui/react-nodegui#6]
Not seeing it in the docs or example repos. Is this not available yet? I'm eager to try this out, so thanks for your work and sharing it.

**Comment by krestaino** [comment]
Never mind.

https://github.com/nodegui/nodegui#building

**Comment by master-atul** [comment]
Yes the packaging process is under development.  You should hear something about it by next week for sure 😬

**Comment by krestaino** [comment]
Awesome, sounds good. I'll keep my eye out!
