### ISSUE TITLE
Cannot resize icon

### ISSUE THREAD

**Issue by talentlessguy** [nodegui/react-nodegui#60]
**Describe the bug**
Icon size is not being changed using `pixmap`

**To Reproduce**
1. `git clone https://github.com/talentlessguy/QuarkPlayer`
2. Run `yarn && yarn dev` in one window, `yarn start` in another window
3. See icon size is not being changed

**Expected behavior**
I expected for icon to increase its size by changing width and height

**Screenshots**

![image](https://user-images.githubusercontent.com/35937217/68772721-54935400-063b-11ea-98c4-4f47f282b5fe.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - NodeGUI version: 0.5.1
 - React NodeGUI version: 0.2.2
 - OS Version: Plasma 5.17.2

**Additional context**

Code snippet where I try to resize icon:

```ts
import { QIcon } from '@nodegui/nodegui'
import icon from '../../assets/play.png'

const Icon = new QIcon(`${__dirname}/${icon}`)

Icon.pixmap(100, 100)
```

**Comment by master-atul** [comment]
Could you try `pixmap.scaled(width, height);` ?

https://docs.nodegui.org/docs/api/QPixmap#pixmapscaledwidth-height-aspectratiomode

**Comment by talentlessguy** [comment]
@master-atul 

```ts
const Icon = new QIcon(`${__dirname}/${icon}`)

Icon.scaled() // trying to call the method
```

```
Property 'scaled' does not exist on type 'QIcon'.
```

**Comment by master-atul** [comment]
Alright, seems like a missing functionality. Will add it in the next release.  @talentlessguy

**Comment by talentlessguy** [comment]
> Alright, seems like a missing functionality. Will add it in the next release. @talentlessguy

awesome! looking forward to this feature

**Comment by talentlessguy** [comment]
@master-atul 

while this functionality is being implemented in `react-nodegui`, is it possible to achieve it with plain `nodegui` with combination of `react-nodegui`?

**Comment by master-atul** [comment]
Actually yes. 
You could add a ref to the react-nodegui component

like so:
```js
const buttonRef = React.createRef<QPushButton>();
useEffect(()=>{
buttonRef.setIconSize(new QSize(23,23));
},[]);
...
...
<Button ref={buttonRef} />
```
For the timebeing.

**Comment by master-atul** [comment]
iconSize prop is now available in 0.2.7 of react-nodegui for button, checkbox and radiobuttons

**Comment by talentlessguy** [comment]
> iconSize prop is now available in 0.2.7 of react-nodegui for button, checkbox and radiobuttons

How can I use it? Please give an example

**Comment by master-atul** [comment]
Something like this :
```
import React from "react";
import { Renderer, Button, Window, View } from "@nodegui/react-nodegui";
import { QIcon, QSize } from "@nodegui/nodegui";

const icon = new QIcon(
  "/Users/atulr/Project/nodegui/react-nodegui/extras/assets/nodegui_white.png"
);

const App = () => {
  return (
    <Window>
      <View style={containerStyle}>
        <Button
          style={buttonStyle}
          text={"Hello"}
          icon={icon}
          iconSize={new QSize(200, 200)}
        />
      </View>
    </Window>
  );
};
```

**Comment by ADARSHYODHA** [comment]
Hello @a7ul
 Can u tell me how can we make a messagebox or alertbox in react-nodegui
