### ISSUE TITLE
[help wanted]Is there any example for how to use QSystemTrayIcon with react-nodegui?

### ISSUE THREAD

**Issue by leopku** [nodegui/react-nodegui#74]
**Is your feature request related to a problem? Please describe.**
Big thanks for any help for using QSystemTrayIcon with react-nodegui.

**Describe the solution you'd like**
Using QSystemTrayIcon with react-nodegui.

**Comment by master-atul** [comment]
Since I couldnt find a nice declarative api for  systray its not yet exported out as react-nodegui component. But you could use nodegui version of systray as it is. 
Example can be found here.
https://github.com/nodegui/examples/tree/master/nodegui/systray

**Comment by leopku** [comment]
> Since I couldnt find a nice declarative api for systray its not yet exported out as react-nodegui component. But you could use nodegui version of systray as it is.
> Example can be found here.
> https://github.com/nodegui/examples/tree/master/nodegui/systray

@master-atul Thanks.

I'll wait until react version of systray.

**Comment by master-atul** [comment]
@leopku  You could use the nodegui version of systray at the moment and maybe migrate it to react nodegui one when its added 👍
