### ISSUE TITLE
Error with CMake on macOS (Catalina)

### ISSUE THREAD

**Issue by KirillSaltykov** [nodegui/react-nodegui#76]
**Describe the bug**
When following steps on Getting started block, got an error with CMake.

**To Reproduce**

1. Clone project from GitHub
2. Go to project folder
3. Run `npm install`

**Expected behavior**
Dependencies installed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `macOS`
 - NodeGUI version: `0.6.7`
 - React NodeGUI version: `0.2.6`
 - OS Version: `10.15.1`

**Additional context**
The problem is gone when install CMake using `brew`. I think to add install CMake requirement to Getting started page for not confusing people.

**Comment by master-atul** [comment]
Hi @KirillSaltykov  
The getting started page here: https://react.nodegui.org/docs/guides/getting-started/
mentions cmake as a requirement. Are we missing it somewhere ?

**Comment by KirillSaltykov** [comment]
Hi @master-atul 
Yes, here: https://react.nodegui.org/#quick-start nothing about CMake 🙂
And when I tried to follow steps on this page, I got an error that CMake not found.

**Comment by master-atul** [comment]
Ohh! okay. Thanks for pointing out!

**Comment by siowyisheng** [comment]
On Windows I am also unable to succeed in the "Getting Started". I installed CMake but this fails with many errors.

![cmake error](https://user-images.githubusercontent.com/25425028/72611904-3b25c580-3966-11ea-893e-373805c94970.png)

```
@nodegui/nodegui@0.12.1 build:addon: `cross-env CMAKE_BUILD_PARALLEL_LEVEL=8 cmake-js compile`
```

**Comment by master-atul** [comment]
Hi @KirillSaltykov  Which version of Visual studio do you have installed ?

**Comment by siowyisheng** [comment]
Vs 2017

**Comment by siowyisheng** [comment]
oops sorry I'm still on vs 2015. I'll upgrade and report back. My bad.

**Comment by chrissantamaria** [comment]
Agreed, the requirement should be noted on the quickstart page - just ran into this issue myself. I'm happy to make a pull request and add a brief requirement description if you'd like @master-atul
