### ISSUE TITLE
App suddenly closing itself

### ISSUE THREAD

**Issue by intrnl** [nodegui/react-nodegui#80]
**Describe the bug**
App suddenly closes by itself due to being garbage collected.

Temporary workaround is to use the onInit function to put the reconciler as a global variable, like so.
```tsx
Renderer.render(<App />, {
  onInit: (reconciler) => {
    (global as any)._reconcile = reconciler;
  },
});
```

I know that this is in [FAQ](https://docs.nodegui.org/docs/faq/#my-apps-windowwidgetstray-disappeared-after-a-few-minutes), but it's not clear how you would actually do this in React NodeGUI.

Since the container is put to `Renderer.container`, I suppose there would be no problem with putting a global variable as well?

**To Reproduce**
1. Build any application as normal (best on production mode)
2. Run the app (`npx qode ./dist/index.js`)
3. Wait for several seconds, the app will suddenly close by itself with exit code 0

**Expected behavior**
The app shouldn't close itself.

**Desktop (please complete the following information):**
 - Arch Linux 5.4.0-zen1-1-zen
 - NodeGUI version: 0.6.9 
 - React NodeGUI version: 0.2.7

**Comment by master-atul** [comment]
Hi @intrnl 
I tried the steps you suggested (`even manually ran global.gc()`) for about half an hour. And the app didnt crash. Is there anything more that you are doing in your app?

Also. the steps suggested to solve this might not have any effect.
```
(global as any)._reconcile = reconciler;
```
This is because reconciler is aleady in the module.exports of nodejs which means it wont be garbage collected at all.

Do you have an app source which I can clone and check ?

**Comment by master-atul** [comment]
Also, it would be amazing if you can check this with latest nodegui and react nodegui versions aswell

**Comment by intrnl** [comment]
Tested on latest NodeGUI and React NodeGUI, it still happens.

I've made an [example repo](https://github.com/intrnl/nodegui-test) with the global variable commented.

```
$ npm run build

> test-app@0.1.0 build /home/intrnl/Documents/projects/nodegui-test
> webpack --mode=production --progress

... webpack build output ...

$ npm run start

> test-app@0.1.0 start /home/intrnl/Documents/projects/nodegui-test
> qode --inspect ./dist/index.js

QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Debugger listening on ws://127.0.0.1:9229/df7d2dd5-4648-49ab-b946-aafe3088a0b3
For help, see: https://nodejs.org/en/docs/inspector
Qt exited with 0[intrnl@intrnl nodegui-test]$ 
```

**Comment by slidinghotdog** [comment]
tried the repo from @intrnl and got the same results, app closes after ~8 seconds, only when i run `npm run build` and `npm start` (also with packaged appimage), but no problems with `npm run dev` and `npm start`

```
import React from 'react';
import { Renderer, Window, Text } from '@nodegui/react-nodegui';

class App extends React.Component {
  render () {
    return (
      <Window windowTitle='Test App'>
        <Text>Hello world!</Text>
      </Window>
    )
  }
}
Renderer.render(<App />)
```
trimmed the app a little bit more (removed hot) and the problem continued, but the proposed solution works
```
linux mint 19.2
node 12.13.1
npm 6.13.1

"@nodegui/nodegui": "^0.7.0",
"@nodegui/react-nodegui": "^0.3.0",
```

**Comment by master-atul** [comment]
Yep, I can confirm I can reproduce this issue. 
Seems like webpack bundling is causing some issues here.  Need to dig a bit more deep on why this happens. 

Also can you try with 
```
 <Window windowTitle='Test App'>
    <View>
        <Text>Hello world!</Text> 
     </View>
      </Window>```

and see if you get the same result ?

**Comment by slidinghotdog** [comment]
no changes with `View`, but these 2 examples didn't close:
```
class App extends React.Component {
  state = { count: 0 };
  increase = () => {
    this.setState({ count: this.state.count + 1 });
  };
  componentDidMount() {
    setInterval(this.increase, 1000);
  }
  render() {
    return (
      <Window windowTitle="Test App">
        <Text>{`Hello world! ${this.state.count}`}</Text>
      </Window>
    );
  }
}
```

```
class App extends React.Component {
  state = { count: 0 };
  increase = () => {
    this.setState({ count: this.state.count + 1 });
  };
  render() {
    return (
      <Window windowTitle="Test App">
        <Button on={{clicked:this.increase}}text={`Hello world! ${this.state.count}`}></Button>
      </Window>
    );
  }
}
```
it looks like if theres any listeners it won't get gc..

**Comment by master-atul** [comment]
That explains why default demo example doesnt close. Thanks for the inputs! @slidinghotdog

**Comment by master-atul** [comment]
Okay even adding a simple 
```setInterval(() => {}, 100000);``` at the end of any file. 
Makes the process be alive!

Another test is 
```
setTimeout(() => {
  console.log("times up!");
}, 14000);
```
This make allows the process to stay alive for 14 secs. and after that whenever I run `global.gc()`
via the debugger the app closes.

So my theory is that nodejs process thinks that there are no more instructions for it to execute and then it just closes of.
So whenever a event listener is added it stays alive since it thinks it needs to wait for an instruction.

So I am guessing its not the garbage collection but simple that nodejs thinks it doesnt have any more things to execute.

**Comment by slidinghotdog** [comment]
@master-atul is there any downside if u add @intrnl solution on default config for the renderer?

**Comment by master-atul** [comment]
No I dont think so actually. Let me run few more checks and see which solution to go with

**Comment by slidinghotdog** [comment]
don't know if its a good idea, but if theres something useful to run u could also attach some default listener on mainwindow (when created or closed), or run entire app on listener after main window is created

**Comment by master-atul** [comment]
Released in https://github.com/nodegui/react-nodegui/releases/tag/v0.3.1
