### ISSUE TITLE
How to use useEventHandler

### ISSUE THREAD

**Issue by neosarchizo** [nodegui/react-nodegui#87]
**Is your feature request related to a problem? Please describe.**
I saw how to use Button in [this example](https://github.com/nodegui/react-nodegui-starter/blob/be17c2bf835bdfca4698fc8a04385f1ab5533576/src/components/steptwo.tsx#L6-L10). But I wanna use Button by `useEventHandler`. But I don't know [what deps means](https://github.com/nodegui/react-nodegui/blob/73805844d33487cbb96a8033071102a9802c8e7b/src/hooks/index.ts#L9).
How can I use it?

**Describe the solution you'd like**
Example of it

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by master-atul** [comment]
oh its the same with how you use useffect hook. in reality its actually second param of usememo hook. so it should be an array containing all dependencies

**Comment by neosarchizo** [comment]
I used it like following. It works well!
```es6
import React from 'react'
import {Text, View, Button, ScrollArea, useEventHandler} from '@nodegui/react-nodegui'
import {QPushButtonEvents} from '@nodegui/nodegui'
import open from 'open'

...

const buttonEventHandler = {
  [QPushButtonEvents.clicked]: () => {
    open('https://react.nodegui.org').catch(console.log)
  },
}

....
<Button text="Test" on={useEventHandler(buttonEventHandler, [buttonEventHandler])} />

```

**Comment by master-atul** [comment]
Yep  you could change it to 
```
useEventHandler(buttonEventHandler, [])
```
aswell

Or if u want, u can also skip the use of useEventHandler and pass in the handler object directly (although this will cause minor perf issues)
