### ISSUE TITLE
Merge multiple stylesheets

### ISSUE THREAD

**Issue by neosarchizo** [nodegui/react-nodegui#88]
**Is your feature request related to a problem? Please describe.**
As you know, React can merge multiple stylesheets like following.

```jsx
<View style={styles.container}>
  <Text style={[styles.title, this.props.isActive && styles.activeTitle]} />
</View>
```

But I don't know how to merge multiple stylesheets in react-nodegui.
Because I wanna make some custom components that have own stylesheet can add additional stylesheet, so I need this function. 

**Describe the solution you'd like**
Please add new prop for this.

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by neosarchizo** [comment]
I solved this myself.

```jsx
const viewStyle = `
  flex-direction: 'column';
`

const colorStyle = `
  background-color: 'yellow';
`

...

<View style={viewStyle + colorStyle}>
```

This works well. And if there are duplicated props then last one will overwrite.  
But I'm still looking for how to lint for nodegui style. Hahhh.

**Comment by master-atul** [comment]
Thats a neat solution @neosarchizo 

linting and autocomplete would require a custom babel plugin to be built. (Like in the case of styled components). I do have this in my mind but its not at the very top of the priority list
