### ISSUE TITLE
How to call api on button clicked?

### ISSUE THREAD

**Issue by kkcy** [nodegui/react-nodegui#94]
**Is your feature request related to a problem? Please describe.**
Browsed through both react-nodegui and nodegui, but couldn't find any example.
Tried using axios/http on button click and keyboard listeners but the app crashed with

`FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope`

It worked fine in componentDidMount though.

**Describe the solution you'd like**
Examples or guides for networking

**Describe alternatives you've considered**

**Additional context**

**Comment by kkcy** [comment]
The crash might be related to async/await.
No crashes if the api was called with .then()

**Comment by master-atul** [comment]
Could you create a sample repo so that I can take a look ? @kkcy

**Comment by kkcy** [comment]
hey @master-atul, thanks but installing polyfill and adding `"@babel/plugin-transform-async-to-generator"` seems to fix the problem
