### ISSUE TITLE
 How do I request remote resources in React-nodegui

### ISSUE THREAD

**Issue by Harhao** [nodegui/react-nodegui#95]
When I use the `react-nodegui` to write a desktop application, how do I request remote resources in React-nodegui? like the lifeCycleMethod in react syntax？？

**Comment by master-atul** [comment]
Hi @Harhao by requesting remote resources do you mean fetching data via an API? Then you would do it just like how you would in a react app. U can use the react's lifecycle methods or hooks to call an api usig either axios or node fetch.
